# Generated by Django 2.1.2 on 2019-05-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MD',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sn', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=100)),
                ('measurement', models.FloatField(blank=True, default=None, null=True)),
                ('madefrom', models.CharField(default=None, max_length=100)),
                ('madein', models.CharField(default=None, max_length=100)),
                ('date_of_production', models.DateField(blank=True, default=None, null=True)),
                ('quality_gurantee', models.DateField(blank=True, default=None, null=True)),
                ('size', models.IntegerField(blank=True, default=None, null=True)),
                ('shoulder', models.FloatField(blank=True, default=None, null=True)),
                ('chest', models.FloatField(blank=True, default=None, null=True)),
                ('sleeve_len', models.FloatField(blank=True, default=None, null=True)),
                ('sleeve_end', models.FloatField(blank=True, default=None, null=True)),
                ('armpit', models.FloatField(blank=True, default=None, null=True)),
                ('top_size', models.FloatField(blank=True, default=None, null=True)),
                ('waist', models.FloatField(blank=True, default=None, null=True)),
                ('thigh', models.FloatField(blank=True, default=None, null=True)),
                ('bottom', models.FloatField(blank=True, default=None, null=True)),
                ('crotch', models.FloatField(blank=True, default=None, null=True)),
                ('tail', models.FloatField(blank=True, default=None, null=True)),
                ('down_size', models.FloatField(blank=True, default=None, null=True)),
                ('shoes_size', models.IntegerField(blank=True, default=None, null=True)),
                ('ball_foot', models.IntegerField(blank=True, default=None, null=True)),
                ('insole', models.FloatField(blank=True, default=None, null=True)),
                ('heel', models.FloatField(blank=True, default=None, null=True)),
                ('front_heel', models.FloatField(blank=True, default=None, null=True)),
                ('shoes_height', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.MD')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Seller'),
        ),
    ]
