# Generated by Django 2.1.2 on 2019-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190604_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='front_heel',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='heel',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='insole',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoes_height',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
